# Generated by Django 4.2.30 on 2026-07-02 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='category',
            field=models.CharField(choices=[('general', 'Общее'), ('games', 'Игры'), ('movies', 'Фильмы'), ('music', 'Музыка'), ('social', 'Общение')], default='general', max_length=30),
        ),
    ]
