# Generated by Django 4.2.30 on 2026-07-06 18:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_userprofile_roominvitation_aiintegration'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomAIIntegration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('gpt', 'ChatGPT'), ('grok', 'Grok'), ('deepseek', 'DeepSeek'), ('qwen', 'Qwen'), ('claude', 'Claude')], max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_integrations', to='chat.room')),
            ],
            options={
                'unique_together': {('room', 'provider')},
            },
        ),
    ]
